const sort=p=>[...new Set(p.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de'));const activity=v=>ACT.includes(v)?v:'joggen';const num=v=>parseFloat(String(v||'').replace(',','.'));
function durationSeconds(v){const s=String(v||'').trim();if(!s)return NaN;let p=s.split(':');if(p.length===2&&p.every(x=>/^\d+$/.test(x))){let [m,sec]=p.map(Number);return sec<60?m*60+sec:NaN}if(p.length===3&&p.every(x=>/^\d+$/.test(x))){let [h,m,sec]=p.map(Number);return m<60&&sec<60?h*3600+m*60+sec:NaN}let x=s.match(/^(\d+)\s*[,\.]\s*(\d{1,2})$/);if(x){let sec=+x[2];return sec<60?(+x[1])*60+sec:NaN}return /^\d+$/.test(s)?(+s)*60:NaN}
function formatDuration(v){let t=durationSeconds(v);return t>=0?`${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`:String(v||'')}
function pace(km,d){let k=num(km),t=durationSeconds(d);if(!(k>0&&t>0))return'';let p=Math.round(t/k);return`${Math.floor(p/60)}:${String(p%60).padStart(2,'0')}`}
function normalize(d){let x=Object.assign(blank(),d||{});x.aktivitaet=activity(x.aktivitaet);x.istKm=x.istKm==null?'':String(x.istKm);x.minuten=x.aktivitaet==='joggen'&&x.minuten!=null?formatDuration(String(x.minuten)):'';x.pace=x.aktivitaet==='joggen'?pace(x.istKm,x.minuten):'';['sprints','seil','kraft','pass','jonglieren','video','rueckmeldung'].forEach(k=>x[k]=!!x[k]);x.jonglierenAnzahl=x.jonglierenAnzahl==null?'':String(x.jonglierenAnzahl);return x}
function load(){let s;try{s=JSON.parse(localStorage.getItem(KEY))}catch{}if(!s)for(const k of OLD){try{s=JSON.parse(localStorage.getItem(k))}catch{}if(s)break}if(!s||!Array.isArray(s.players))s={players:[...DEFAULT],weeks:{},sent:{}};s.players=s.players.map(n=>n==='Piotr'?'Piotrek':n);DEFAULT.forEach(n=>{if(!s.players.includes(n))s.players.push(n)});s.players=sort(s.players);s.weeks=s.weeks||{};s.sent=s.sent||{};if(s.sent.Piotr&&!s.sent.Piotrek)s.sent.Piotrek=s.sent.Piotr;delete s.sent.Piotr;s.players.forEach(n=>s.sent[n]=!!s.sent[n]);WEEKS.forEach(w=>{s.weeks[w.id]=s.weeks[w.id]||{};if(s.weeks[w.id].Piotr){s.weeks[w.id].Piotrek=s.weeks[w.id].Piotr;delete s.weeks[w.id].Piotr}s.players.forEach(n=>s.weeks[w.id][n]=normalize(s.weeks[w.id][n]))});return s}
const q=(row,r)=>row.querySelector(`[data-role="${r}"]`);const yes=el=>el&&el.checked?'Ja':'Nein';
function players(){return sort([...document.querySelectorAll('.summary-btn')].map(b=>b.dataset.player))}
function save(){const s={players:players(),weeks:{},sent:{}};document.querySelectorAll('.sent-check').forEach(i=>s.sent[i.dataset.player]=i.checked);document.querySelectorAll('table[data-week]').forEach(t=>{s.weeks[t.dataset.week]={};t.querySelectorAll('tbody tr').forEach(r=>{let a=q(r,'activity').value,d=a==='joggen'?q(r,'min').value:'';s.weeks[t.dataset.week][r.querySelector('.name').textContent.trim()]={aktivitaet:a,istKm:q(r,'km').value,minuten:d,pace:a==='joggen'?q(r,'pace').value:'',sprints:q(r,'sprints').checked,seil:q(r,'seil').checked,kraft:q(r,'kraft').checked,pass:q(r,'pass').checked,jonglieren:q(r,'jonglieren').checked,jonglierenAnzahl:q(r,'jonglierenAnzahl').value,video:q(r,'video').checked,rueckmeldung:q(r,'rueckmeldung').checked}})});localStorage.setItem(KEY,JSON.stringify(s));updateSummaryButtons();if(typeof updatePaceViews==='function')updatePaceViews()}
function copy(text,button,done){const ok=()=>{let old=button.innerHTML;button.textContent=done;setTimeout(()=>button.innerHTML=old,1500)};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(ok).catch(fallback);else fallback();function fallback(){let a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();try{document.execCommand('copy');ok()}catch{alert('Kopieren nicht möglich. Bitte manuell kopieren.')}a.remove()}}
function requireCode(){if(Date.now()<validUntil)return true;let x=prompt('Bitte Sicherheits-Code eingeben:');if(x===null)return false;if(x.trim()===CODE){validUntil=Date.now()+180000;return true}alert('Falscher Code.');return false}
function field(input,dash,show){input.hidden=!show;input.disabled=!show;dash.hidden=show}
function mode(r,clear=false){let a=q(r,'activity').value,j=a==='joggen',tr=a==='training',km=q(r,'km'),d=q(r,'min'),p=q(r,'pace');if(clear&&a==='fahrrad'){d.value='';p.value=''}field(km,q(r,'km-na'),!tr);field(d,q(r,'min-na'),j);field(p,q(r,'pace-na'),j);q(r,'soll').hidden=tr;q(r,'soll-na').hidden=!tr;r.querySelectorAll('[data-task]').forEach(i=>{const isFeedback=i.dataset.role==='rueckmeldung';field(i,i.parentElement.querySelector('.na'),isFeedback||!tr)});r.classList.toggle('training',tr);if(j)p.value=pace(km.value,d.value)}
const task=(role,type='checkbox',extra='')=>`<td><input type="${type}" ${extra} data-role="${role}" data-task><span class="na" hidden>—</span></td>`;
