function summaryButtons(p,sent={}){let box=document.getElementById('summary-buttons');box.innerHTML='';sort(p).forEach(n=>{let item=document.createElement('div'),b=document.createElement('button'),label=document.createElement('label'),check=document.createElement('input');item.className='summary-player';b.className='summary-btn';b.dataset.player=n;b.onclick=()=>copy(summary(n),b,`${n} ✔`);check.type='checkbox';check.className='sent-check';check.dataset.player=n;check.checked=!!sent[n];check.setAttribute('aria-label',`${n} Übersicht gesendet`);check.onchange=save;label.className='sent-toggle';label.append(check,document.createTextNode(' gesendet'));item.append(b,label);box.appendChild(item)});updateSummaryButtons();initPaceViews()}
function data(n,id){let t=document.querySelector(`table[data-week="${id}"]`),r=[...t.tBodies[0].rows].find(x=>x.querySelector('.name').textContent.trim()===n);return{soll:t.dataset.km,a:q(r,'activity').value,km:q(r,'km').value||'-',d:q(r,'min').value||'-',p:q(r,'pace').value||'-',sprints:yes(q(r,'sprints')),seil:yes(q(r,'seil')),kraft:yes(q(r,'kraft')),pass:yes(q(r,'pass')),jong:yes(q(r,'jonglieren')),anz:q(r,'jonglierenAnzahl').value||'-',video:yes(q(r,'video')),rueckmeldung:yes(q(r,'rueckmeldung'))}}
function result(d){if(d.a==='training')return{done:8,total:8,percent:100};let done=(num(d.km)>0?2:0)+['sprints','seil','kraft','pass','jong'].filter(k=>d[k]==='Ja').length+(d.video==='Ja'?.5:0)+(d.rueckmeldung==='Ja'?.5:0);return{done,total:8,percent:Math.round(done/8*100)}}
function playerPercent(n){let done=0,total=0;WEEKS.forEach(w=>{let r=result(data(n,w.id));done+=r.done;total+=r.total});return total?Math.round(done/total*100):0}
function percentClass(p){return p>=80?'pct-green':p>=60?'pct-yellow':p>=30?'pct-orange':'pct-red'}
function updateSummaryButtons(){document.querySelectorAll('.summary-btn').forEach(b=>{let p=playerPercent(b.dataset.player);b.classList.remove('pct-green','pct-yellow','pct-orange','pct-red');b.classList.add(percentClass(p));b.innerHTML=`<span>${b.dataset.player}</span><span class="pct">${p} %</span>`})}
function pointText(v){return Number.isInteger(v)?String(v):String(v).replace('.',',')}
function pointSuffix(ok,v){return ok?` (+${pointText(v)} ${v===1?'Punkt':'Punkte'})`:''}
function psText(p){if(p===100)return'Hervorragend – die maximale Punktzahl wurde erreicht.';if(p>=80)return'Starke Leistung – fast alle möglichen Punkte wurden erreicht.';if(p>=60)return'Ein großer Teil der möglichen Punkte wurde erreicht.';if(p>=30)return'Ein Teil der möglichen Punkte wurde erreicht. Es ist noch Luft nach oben.';return'Nur wenige der möglichen Punkte wurden erreicht.'}
function summary(n){let out=`D1 Sommerferien-Vorbereitung\n${n}\n\n`,done=0,total=0;WEEKS.forEach(w=>{let d=data(n,w.id),r=result(d),kmDone=num(d.km)>0;done+=r.done;total+=r.total;if(d.a==='training'){out+=`Woche ${w.id}:\n⚽ Training bei der SSVg begonnen${pointSuffix(true,8)}\n⭐ Bewertung: ${pointText(r.done)} von ${r.total} Punkten – ${r.percent} %\n\n`;return}out+=`Woche ${w.id} (Soll ${d.soll} km Joggen oder vergleichbar Fahrrad):\n`;out+=d.a==='fahrrad'?`🚴 Fahrrad: ${d.km} km${pointSuffix(kmDone,2)}\n`:`🏃 Joggen: ${d.km} km in ${d.d} Min${d.p!=='-'?` (Pace: ${d.p} min/km)`:''}${pointSuffix(kmDone,2)}\n`;out+=`⚡ Sprinttraining: ${d.sprints}${pointSuffix(d.sprints==='Ja',1)}\n🪢 Seilspringen: ${d.seil}${pointSuffix(d.seil==='Ja',1)}\n💪 Kraftübungen: ${d.kraft}${pointSuffix(d.kraft==='Ja',1)}\n⚽ Pass-Challenge: ${d.pass}${pointSuffix(d.pass==='Ja',1)}\n🎯 Jonglieren: ${d.jong} (Anzahl: ${d.anz})${pointSuffix(d.jong==='Ja',1)}\n🎥 Video gesendet: ${d.video}${pointSuffix(d.video==='Ja',.5)}\n📩 Rückmeldung gegeben: ${d.rueckmeldung}${pointSuffix(d.rueckmeldung==='Ja',.5)}\n⭐ Bewertung: ${pointText(r.done)} von ${r.total} Punkten – ${r.percent} %\n\n`});let percent=total?Math.round(done/total*100):0;out+=`📊 Gesamtergebnis Sommerferien\n⭐ ${pointText(done)} von ${total} Punkten erreicht\n📈 Erfolgsquote: ${percent} %\n\nPS: ${psText(percent)}`;return out.trim()}

function paceSeconds(v){let m=String(v||'').trim().match(/^(\d+):(\d{2})$/);if(!m)return NaN;let sec=+m[2];return sec<60?(+m[1])*60+sec:NaN}
function paceEntries(weekId){let out=[];players().forEach(n=>{let d=data(n,weekId),ps=paceSeconds(d.p),km=num(d.km),dur=durationSeconds(d.d);if(d.a==='joggen'&&Number.isFinite(ps)&&ps>0&&km>0&&dur>0)out.push({name:n,pace:d.p,paceSec:ps,km:d.km,duration:formatDuration(d.d)})});out.sort((a,b)=>a.paceSec-b.paceSec||a.name.localeCompare(b.name,'de'));let last=null,rank=0;out.forEach((x,i)=>{if(last===null||x.paceSec!==last)rank=i+1;x.rank=rank;last=x.paceSec});return out}
function medal(rank){return rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':`${rank}.`}
function fillPaceSelectors(){let w=document.getElementById('pace-week'),p=document.getElementById('pace-player');if(!w||!p)return;let oldW=w.value||'1',oldP=p.value;w.innerHTML=WEEKS.map(x=>`<option value="${x.id}">Woche ${x.id}</option>`).join('');w.value=WEEKS.some(x=>String(x.id)===oldW)?oldW:'1';let ps=players();p.innerHTML=ps.map(n=>`<option value="${n.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}">${n}</option>`).join('');if(oldP&&ps.includes(oldP))p.value=oldP;else if(ps.length)p.value=ps[0]}
function renderPaceRanking(){let sel=document.getElementById('pace-week'),box=document.getElementById('pace-ranking');if(!sel||!box)return;let entries=paceEntries(sel.value);if(!entries.length){box.innerHTML='<p class="small">Für diese Woche gibt es noch keine gültigen Jogging-Paces.</p>';return}let rows=entries.map(x=>`<tr><td>${medal(x.rank)}</td><td>${x.name}</td><td><strong>${x.pace} min/km</strong></td><td>${x.km} km</td><td>${x.duration}</td></tr>`).join('');box.innerHTML=`<div class="wrap pace-wrap"><table class="pace-table"><thead><tr><th>Platz</th><th>Spieler</th><th>Pace</th><th>Strecke</th><th>Zeit</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function playerWeekPace(name,w){let d=data(name,w.id),ps=paceSeconds(d.p);if(d.a!=='joggen'||!Number.isFinite(ps)||ps<=0)return null;let entries=paceEntries(w.id),me=entries.find(x=>x.name===name);return me?{week:w.id,pace:d.p,paceSec:ps,rank:me.rank,km:d.km,duration:formatDuration(d.d)}:null}
function diffText(first,last){let diff=last.paceSec-first.paceSec;if(diff===0)return'±0:00 min/km';let sign=diff<0?'−':'+';let s=Math.abs(diff);return`${sign}${Math.floor(s/60)}:${String(s%60).padStart(2,'0')} min/km`}
function renderPlayerPace(){let sel=document.getElementById('pace-player'),sum=document.getElementById('pace-player-summary'),box=document.getElementById('pace-player-history');if(!sel||!sum||!box)return;let n=sel.value;if(!n){sum.innerHTML='';box.innerHTML='<p class="small">Keine Spieler vorhanden.</p>';return}let list=WEEKS.map(w=>playerWeekPace(n,w)).filter(Boolean);if(!list.length){sum.innerHTML='';box.innerHTML='<p class="small">Für diesen Spieler gibt es noch keine gültigen Jogging-Paces.</p>';return}let best=[...list].sort((a,b)=>a.paceSec-b.paceSec)[0],first=list[0],last=list[list.length-1];sum.innerHTML=`<div class="pace-summary"><strong>Beste Pace:</strong> ${best.pace} min/km (Woche ${best.week})<br><strong>Entwicklung:</strong> ${diffText(first,last)} von Woche ${first.week} bis Woche ${last.week}</div>`;let rows=WEEKS.map(w=>{let x=playerWeekPace(n,w);return x?`<tr><td>Woche ${w.id}</td><td><strong>${x.pace} min/km</strong></td><td>${x.rank}.</td><td>${x.km} km</td><td>${x.duration}</td></tr>`:`<tr><td>Woche ${w.id}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>`}).join('');box.innerHTML=`<div class="wrap pace-wrap"><table class="pace-table"><thead><tr><th>Woche</th><th>Pace</th><th>Platz</th><th>Strecke</th><th>Zeit</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function updatePaceViews(){if(!document.getElementById('pace-week'))return;fillPaceSelectors();renderPaceRanking();renderPlayerPace()}
function initPaceViews(){let w=document.getElementById('pace-week'),p=document.getElementById('pace-player');if(!w||!p)return;fillPaceSelectors();w.onchange=renderPaceRanking;p.onchange=renderPlayerPace;renderPaceRanking();renderPlayerPace()}
